### ISSUE TITLE
No preview shows, "An Error Occurred  - We're sorry, but for some reason we can't open this for you."

### ISSUE THREAD

**Issue by reneenoble** [jqnatividad/ckanext-officedocs#5]
I have installed as per the instructions.  I am able to add in this view, but I don't get the preview.  I get an error, you can check it out here.  

http://52.64.153.184/dataset/ms-test/resource/35e419b6-9bbc-49e7-9e03-59b7374720c1?view_id=8dcc496a-9365-41fe-8561-4e4e4b4a2276

The "learn more" link doesn't lead to anywhere with useful information. 
The link should be http://r.office.microsoft.com/r/rlidowaviewhelp but it redirect to here  https://products.office.com/en-AU/

**Comment by rossjones** [comment]
On trying this specific file, I got a different error - no idea why....

```
There is something in your workbook that we don't understand. Try opening and saving the workbook in a newer version of Excel.
```

There's no obvious way to know that the office viewer has failed, but perhaps I missed something.

The output of ```file``` is below..

```
CDF V2 Document, Little Endian, Os: Windows, Version 6.0, Code page: 1252, Author: X X, Last Saved By: X X, Name of Creating Application: Microsoft Excel, Last Printed: Sun Mar 30 05:11:42 2014, Create Time/Date: Sun Mar  2 06:56:07 2014, Last Saved Time/Date: Tue Jul  1 05:58:43 2014, Security: 0
```

The only thing that stands out to me here is that it is identified as a compound document format (CDF) instead of Excel. Do you know if this spreadsheet was created by a library instead of Excel?

**Comment by reneenoble** [comment]
I'm not sure how that file was created (I got it off a gov ckan website). 

But I've put up some more, 1 created in excel, 1 in excel on line.  I've also included at docx file and a powerpoint file.  All of them have the same error.

**Comment by rossjones** [comment]
I think this is most likely that it's requesting a https:// url inside a site without, and browsers are complaining.

```
Blocked a frame with origin "https://view.officeapps.live.com" from accessing a frame with origin "http://52.64.153.184".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
```

I notice in master now ( https://github.com/jqnatividad/ckanext-officedocs/blob/master/ckanext/officedocs/templates/officedocs/preview.html#L2 ) it is using the http:// url.  This may fix your problem.  Better long-term solution may be to use :// instated of being explicit.

**Comment by rossjones** [comment]
https://github.com/jqnatividad/ckanext-officedocs/pull/6 should fix this.

**Comment by reneenoble** [comment]
Nope still having the same problem.  I re-cloned the repo, then discovered the change you said hadn't clone with master, so I put in the change my self.  Restarted ckan, added a new dataset and it still has an error  http://52.64.153.184/dataset/excel2/resource/f30dbbd0-92ce-4f4b-8762-69455fea382e?view_id=e22cb6ca-5626-472b-b6dd-ee5bd7dffcf7

**Comment by rossjones** [comment]
Turns out Excel online doesn't like IP addresses.
I set up a duckdns.org entry (at xlstest.duckdns.org) and changed the HTML on the page - loaded fine.

Perhaps try duckdns or something similar so that the site has a domain?

**Comment by reneenoble** [comment]
Thanks! It does seem to work with documents that are linked (and thus have  a domain name) rather than ones stored on our database with the IP address.  We'll have a proper domain name when we go into production, so all will e good then :D 

Thanks!!

**Comment by basirebadi** [comment]
Exactly, manually uploading of files will not preview / display , but once you launched your website, then it will work, for local environment please choose the URL option, that's work perfect.
